Issue #2052 showed that BadResponse can be ambiguous
If the exception happens during request serialization,

This commit introduces a BadRequest pipelinefailure and audittrail event and improves DebugInformation

Improves the exception message by introducing a clear separation
between `BadResponse` and a new stage in the pipeline `BadRequest`.

If the pipeline failure reason is `Unexpected` we attempt to fetch a
more useful failure reason from the audit trail.

Another subtle change is that the `DebugInformation` printed a step
number that is 0 based. Since this a message intendend for humans and
humans read ordinals starting from 1. This now starts at 1 and we
print the step number in the audit trail too.

New `DebugInformation`:

```
System.Exception: # FailureReason: Unrecoverable/Unexpected BadRequest
while attempting POST http://localhost:9200/_bulk
 - [1] PingSuccess: Node: http://localhost:9200/ Took: 00:00:00.0156239
 - [2] BadRequest: Node: http://localhost:9200/ Exception:
   InvalidOperationException Took: 00:00:00.0997982
System.InvalidOperationException: Method may only be called on a Type
for which Type.IsGenericParameter is true.
...
...
...
```

Conflicts:
	src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs
	src/Elasticsearch.Net/Connection/InMemoryConnection.cs
	src/Tests/Tests.csproj